### ISSUE TITLE
No babybuddy entities available following update to v2.5.0

### ISSUE THREAD

**Issue by jampez77** [jcgoette/baby_buddy_homeassistant#69]
I recently updated HA to 2022.6.6 and all BB entities are now unavailable. The logs show the following error:

`2022-06-16 10:18:35 ERROR (MainThread) [custom_components.babybuddy] Unexpected error fetching babybuddy data: 'pumping'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/babybuddy/__init__.py", line 187, in async_update
    endpoint_data = await self.client.async_get(
  File "/config/custom_components/babybuddy/client.py", line 43, in async_get
    url = self.endpoints[endpoint]
KeyError: 'pumping'`

## System Health

version | core-2022.6.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.12
os_name | Linux
os_version | 5.15.45
arch | aarch64
timezone | Europe/London

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.3
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 113.9 GB
disk_used | 31.4 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.4.0), Samba share (9.7.0), Log Viewer (0.9.1), Home Assistant Google Drive Backup (0.103.1), SSH & Web Terminal (8.0.3), Node-RED (8.1.2), Mosquitto broker (6.1.2), Visual Studio Code (3.1.0), MariaDB (2.4.0), Ring-MQTT with Video Streaming (5.0.2), Zigbee2mqtt (1.25.2-1), Baby Buddy (1.10.2.3), ESPHome (2022.6.0), File editor (5.3.3)

</details>

**Comment by jampez77** [comment]
Closing this as it looks like it's actually an issue with [addon-babybuddy](https://github.com/OttPeterR/addon-babybuddy) not being updated to latest BB.
